server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///D://Temp_Downloads//config"
        git:
          uri: "https://github.com/gbshekhar/microservices-eazybytes-config.git"
          default-label: main
          time-out: 5
          clone-start: true
          force-pull: true
  rabbitmq:
    uri: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "fjiukejidljsdkfu"