build:
  version: "1.0.0"

cards:
  message: "Welcome to EazyBank accounts related Local APIs - Prod"
  contactDetails:
    name: "Prod"
    email: "Prod@gmail.com"
  onCallSupport:
    - 8333032079
    - 8333032079