build:
  version: 3.0

loans:
  message: "Welcome to EazyBank accounts related Local APIs - QA"
  contactDetails:
    name: "QA"
    email: "qa@gmail.com"
  onCallSupport:
    - 8333032079
    - 8333032079